# The URL the site will be built for
# base_url = "https://k94.ch"

base_url = "https://k94.ch/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
generate_feed = true
build_search_index = false

highlight_code = true
highlight_theme = "inspired-github"


external_links_target_blank = true

taxonomies = [
    { name = "rust", feed = true},
    { name = "tech", feed = true},
    { name = "fit", feed = true},
    { name = "misc", feed = true},
    { name = "tags", feed = true},
]

[extra]
# Put all your custom variables here
